routes:
- path: ""
  target: $(@D)/index.html
- path: part01
  target: $(@D)/part01.html
- path: part02
  target: $(@D)/part02.html
- path: part03
  target: $(@D)/part03.html
- path: part04
  target: $(@D)/part04.html
- path: part05
  target: $(@D)/part05.html
- path: part06
  target: $(@D)/part06.html
- path: q-and-a
  target: $(@D)/q-and-a.html
- path: addenda
  target: $(@D)/addenda.html
- path: css/buttondown.css
  target: resources/buttondown.css
- path: js/main.js
  target: resources/main.js

targets:
- path: $(@D)/index.html
  tool: pandoc
  inputs:
  - index.md
  dependencies:
  - .pansite.yaml
  - resources/footer.html
  - resources/header.html
  - resources/nav.html
- path: "$(@D)/%.html"
  tool: pandoc
  inputs:
  - "%.md"
  dependencies:
  - .pansite.yaml
  - resources/footer.html
  - resources/header.html
  - resources/nav.html

tool-settings:
  pandoc:
    include-in-header-path: resources/header.html
    include-before-body-path: resources/nav.html
    include-after-body-path: resources/footer.html
    number-sections: true
    table-of-contents: true
    template-path: resources/template.html
    vars:
    - [css, css/buttondown.css]
